### ISSUE TITLE
Does `miniaturo` automatically register with tumbler?

### ISSUE THREAD

**Issue by martisj** [dbrgn/miniaturo#14]
First off; thanks for taking the time to Rustify the raw-thumbnailer! :raised_hands: 

I am wondering how to check that miniaturo is running in tumbler?

**Comment by dbrgn** [comment]
Hm, I don't think miniaturo needs to register itself in any way, as long as it can be found on your $PATH. Maybe you could check the output of `ps aux` while thumbnails are being generated?

**Comment by martisj** [comment]
hmm, well I don't know when thumbnails are being generated, how can I start thumbnail generation?

**Comment by dbrgn** [comment]
For example by opening a directory containing raw files in your file browser (e.g. Nautilus or Thunar), I think.

**Comment by martisj** [comment]
Wow! Ok I had set the max file size limit for thumbnails in Thunar to 10MiB. However I can't see `miniaturo` running when filtering in `htop` on `miniaturo`.
Where is `miniaturo` installed? I can't find the path either

**Comment by dbrgn** [comment]
>  Where is `miniaturo` installed? I can't find the path either

Well, how did you install miniaturo? 😄 I can't know where you put the file...
