### ISSUE TITLE
miniaturo will not build with latest libopenraw

### ISSUE THREAD

**Issue by dguertin** [dbrgn/miniaturo#17]
I'm trying to get Canon CR3 RAW thumbnails to show in the Nemo file manager. miniaturo looks like a promising tool for this, but I cannot get it to build. According to the docs, I need libopenraw 0.3. So I've downloaded and built libopenraw 0.3.7 from GitHub, which installs the library libopenraw.so.10.0.0. I'm confused the by the version discrepancy, but that's what it does. Then when I run `cargo test` for miniaturo, it fails with 

`error: could not find system library 'libopenraw-0.3' required by the 'libopenraw-sys' crate`.

I have included the directory where the library is installed, /usr/local/lib, in PKG_CONFIG_PATH.

Suggestions to get this to install?

**Comment by dbrgn** [comment]
Hi @dguertin! First, check out how libopenraw 0.3.7 is being installed and used in CI:

https://github.com/dbrgn/miniaturo/blob/main/.github/workflows/ci.yml#L26-L52

There I'm including the library path in `LD_LIBRARY_PATH`. Does that help in your case?

I also just pushed a 0.6.0 version that includes dependency updates. Maybe you could test with that version?

**Comment by dguertin** [comment]
Hi Danilo,

Thanks, that help a lot. I've gotten miniaturo built now (and learned about Rust/Cargo in the process).

I'm still uncertain how to use it, though. My file manager (nemo) still does not show RAW thumbnails, and when I run miniaturo manually, I get:

$ miniaturo -i /home/guertin/Photos/test -o /home/guertin/Photos/test
factory not found
Error: CantOpen

Am I using it wrong, or is there something else I need to do to generate RAW thumbnails?

Thanks!

Dave

________________________________

**Comment by hfiguiere** [comment]
> According to the docs, I need libopenraw 0.3. So I've downloaded and built libopenraw 0.3.7 from GitHub, which installs the library libopenraw.so.10.0.0. I'm confused the by the version discrepancy, but that's what it does. 

Here is the thing: you didn't build libopenraw 0.3.7. You did build from `master` since the soversion is 10.0.0. 

You should download a tarball if you distribution doesn't provide it. 
The official are found here: https://libopenraw.freedesktop.org/libopenraw/
