### ISSUE TITLE
Create official distro packages

### ISSUE THREAD

**Issue by gluckgluckwasserbauch** [dbrgn/miniaturo#19]
This tool is exactly what I needed, since `raw-thumbnailer` isn't maintained anymore and only available up to Fedora 38 (I'm on 39 now).

Sadly, I can't build it on Fedora Silverblue and I'm not capable enough to submit a build myself.
Are there other easier installation methods available?

Could you make an official build for major distros (Arch, Fedora, Debian, etc.)? That would be awesome! :)

**Comment by dbrgn** [comment]
Hi, packaging is the job of packagers 🙂 I don't use Fedora and don't have experience with packaging for Fedora.

On Arch, you can use the [miniaturo-git](https://aur.archlinux.org/packages/miniaturo-git) AUR package for now.

**Comment by lucabotti** [comment]
For Fedora, please check the COPR repository with the following address:

https://copr.fedorainfracloud.org/coprs/decathorpe/miniaturo/

Regards
